// Workout data: eight muscle-group categories, four exercises each.
// Short sessions beat long ones you skip — each category is one heavy compound
// lift plus three accessories, finishing in 35–45 minutes. The schedule deals
// these out across your training days and rotates weekly, so a 4-day week
// covers all eight categories every fortnight.

const WORKOUTS = [
  {
    id: "chest",
    day: "Chest",
    short: "Chest",
    iconName: "dayPush",
    accent: "#FF4D6D",
    title: "Chest",
    focus: "Pecs, Front Delts, Triceps",
    warmup: "5 min brisk walk or bike + 2 sets of band pull-aparts and 10 slow push-ups",
    exercises: [
      { name: "Barbell or Dumbbell Bench Press", videoId: "4Y2ZdHCOXok", sets: 4, reps: "8–10", rest: "90s", muscle: "Chest, Triceps", cue: "Lower bar to mid-chest, drive feet into floor, press up." },
      { name: "Incline Dumbbell Press", videoId: "awEEyL5zGvU", sets: 3, reps: "10–12", rest: "75s", muscle: "Upper Chest", cue: "30–45° bench. Control the descent, press up and slightly in." },
      { name: "Chest Dip", videoId: "uaQZ2S9D8WY", sets: 3, reps: "8–12", rest: "75s", muscle: "Lower Chest", cue: "Lean the torso forward, elbows flare slightly, stop at a deep stretch." },
      { name: "Push-Up (finisher)", videoId: "WDIpL0pjun0", sets: 2, reps: "AMRAP", rest: "60s", muscle: "Chest, Core", cue: "Straight line head to heels, full range of motion." },
    ],
    cardioFinisher: "Optional: 10–15 min incline treadmill walk (fat-loss boost)",
  },
  {
    id: "back",
    day: "Back",
    short: "Back",
    iconName: "dayPull",
    accent: "#2E9BFF",
    title: "Back",
    focus: "Lats, Mid Back, Biceps",
    warmup: "5 min row or bike + band pull-aparts x15 + dead hangs 2 × 20s",
    exercises: [
      { name: "Pull-Up or Lat Pulldown", videoId: "vw5Xmu5CIew", sets: 4, reps: "8–10", rest: "90s", muscle: "Lats, Biceps", cue: "Pull elbows down and back, chest to bar/handle, control the return." },
      { name: "Barbell or Dumbbell Row", videoId: "tLnlWj7LQ34", sets: 3, reps: "10–12", rest: "75s", muscle: "Mid Back", cue: "Hinge forward, flat back, pull elbows past torso, squeeze shoulder blades." },
      { name: "Seated Cable Row", videoId: "4mRy8U542Fo", sets: 3, reps: "10–12", rest: "75s", muscle: "Mid Back", cue: "Chest up, drive elbows back, avoid leaning too far back." },
      { name: "Face Pull", videoId: "3pToT5_DUiY", sets: 3, reps: "15", rest: "60s", muscle: "Rear Delts", cue: "Pull to eye level, rotate hands, squeeze shoulder blades together." },
    ],
    cardioFinisher: "Optional: 10 min rowing machine, steady pace",
  },
  {
    id: "shoulders",
    day: "Shoulders",
    short: "Delts",
    iconName: "dayPress",
    accent: "#FFB020",
    title: "Shoulders",
    focus: "Front, Side & Rear Delts",
    warmup: "5 min bike + arm circles and band pull-aparts x15 each",
    exercises: [
      { name: "Seated Dumbbell Shoulder Press", videoId: "fuQpuu--bMI", sets: 4, reps: "8–10", rest: "90s", muscle: "Shoulders", cue: "Keep ribs down, press straight overhead without arching lower back." },
      { name: "Dumbbell Lateral Raise", videoId: "pgrWjBfaFe8", sets: 4, reps: "12–15", rest: "60s", muscle: "Side Delts", cue: "Slight elbow bend, raise to shoulder height, lead with elbows." },
      { name: "Reverse Fly", videoId: "4Xr7bKE_fxE", sets: 3, reps: "15", rest: "60s", muscle: "Rear Delts", cue: "Slight bend in elbows, lift arms out to the sides, squeeze at top." },
      { name: "Face Pull", videoId: "3pToT5_DUiY", sets: 3, reps: "15", rest: "45s", muscle: "Rear Delts, Rotators", cue: "Pull to eye level, rotate hands, squeeze shoulder blades together." },
    ],
    cardioFinisher: "Optional: 10 min incline walk",
  },
  {
    id: "arms",
    day: "Arms",
    short: "Arms",
    iconName: "dayCurl",
    accent: "#B14DFF",
    title: "Arms",
    focus: "Biceps, Triceps, Forearms",
    warmup: "5 min bike + 2 light sets of curls and push-downs",
    exercises: [
      { name: "Dumbbell Bicep Curl", videoId: "M2Nbw9tunoY", sets: 4, reps: "10–12", rest: "60s", muscle: "Biceps", cue: "Elbows pinned to sides, no swinging, full range of motion." },
      { name: "Hammer Curl", videoId: "BRVDS6HVR9Q", sets: 3, reps: "12", rest: "60s", muscle: "Biceps, Forearms", cue: "Neutral grip, control the descent." },
      { name: "Triceps Dip", videoId: "uaQZ2S9D8WY", sets: 3, reps: "10–12", rest: "60s", muscle: "Triceps", cue: "Torso upright, elbows point back, lower until upper arms ~parallel." },
      { name: "Overhead Triceps Extension", videoId: "fYqswDVbJDg", sets: 3, reps: "12–15", rest: "60s", muscle: "Triceps", cue: "Elbows stay close to head, full stretch at the bottom." },
    ],
    cardioFinisher: "Optional: 10 min bike sprints (30s on / 30s off)",
  },
  {
    id: "legs",
    day: "Legs",
    short: "Legs",
    iconName: "daySquat",
    accent: "#00D49A",
    title: "Legs",
    focus: "Quads, Glutes, Calves",
    warmup: "5 min bike + bodyweight squats & leg swings x10 each",
    exercises: [
      { name: "Back Squat (or Goblet Squat)", videoId: "bEv6CCg2BC8", sets: 4, reps: "8–10", rest: "120s", muscle: "Quads, Glutes", cue: "Sit hips back and down, knees track over toes, chest up." },
      { name: "Leg Press", videoId: "B6rGDcfyPto", sets: 3, reps: "10–12", rest: "90s", muscle: "Quads, Glutes", cue: "Feet shoulder-width, don't let knees cave, control the negative." },
      { name: "Walking Lunge", videoId: "Pbmj6xPo-Hw", sets: 3, reps: "12 / leg", rest: "75s", muscle: "Quads, Glutes", cue: "Long step, drop back knee toward floor, push through front heel." },
      { name: "Leg Extension", videoId: "tTbJBUKnWU8", sets: 3, reps: "12–15", rest: "60s", muscle: "Quads", cue: "Slow and controlled, squeeze quads hard at the top." },
    ],
    cardioFinisher: "Optional: 15 min incline walk",
  },
  {
    id: "posterior",
    day: "Glutes & Hams",
    short: "Glutes",
    iconName: "dayHinge",
    accent: "#FF6B4D",
    title: "Glutes & Hamstrings",
    focus: "Glutes, Hamstrings, Lower Back",
    warmup: "5 min bike + glute bridges x15 + hip hinges x10",
    exercises: [
      { name: "Romanian Deadlift", videoId: "_oyxCn2iSjU", sets: 4, reps: "8–10", rest: "120s", muscle: "Hamstrings, Glutes", cue: "Soft knees, push hips back, flat back, feel the hamstring stretch." },
      { name: "Hip Thrust", videoId: "xDmFkJxPzeM", sets: 3, reps: "10–12", rest: "90s", muscle: "Glutes", cue: "Shoulders on bench, drive hips up, squeeze glutes hard at the top." },
      { name: "Bulgarian Split Squat", videoId: "DeCnHqrN22U", sets: 3, reps: "10 / leg", rest: "75s", muscle: "Glutes, Quads", cue: "Back foot elevated, most weight on front leg, controlled descent." },
      { name: "Lying or Seated Leg Curl", videoId: "PXG69tKDHoc", sets: 3, reps: "12–15", rest: "60s", muscle: "Hamstrings", cue: "Slow negative, squeeze hamstrings at the top of the curl." },
    ],
    cardioFinisher: "Optional: 20 min steady-state cardio (bike, walk, or elliptical)",
  },
  {
    id: "core",
    day: "Core",
    short: "Core",
    iconName: "dayCore",
    accent: "#00B8D4",
    title: "Core",
    focus: "Abs, Obliques, Deep Core",
    warmup: "5 min brisk walk + cat-cows x10 + dead bugs x10 / side",
    exercises: [
      { name: "Plank", videoId: "mwlp75MS6Rg", sets: 3, reps: "45s hold", rest: "45s", muscle: "Core", cue: "Squeeze glutes, ribs down, straight line head to heels." },
      { name: "Hanging or Lying Knee Raise", videoId: "Pr1ieGZ5atk", sets: 3, reps: "12–15", rest: "60s", muscle: "Lower Abs", cue: "Curl hips up, avoid swinging, control the descent." },
      { name: "Russian Twist", videoId: "onDjITj9AHI", sets: 3, reps: "20 (10/side)", rest: "45s", muscle: "Obliques", cue: "Lean back slightly, rotate from the torso, controlled tempo." },
      { name: "Side Plank", videoId: "NXr4Fw8q60o", sets: 3, reps: "30s / side", rest: "30s", muscle: "Obliques", cue: "Straight line head to feet, hips lifted and stacked." },
    ],
    cardioFinisher: "Optional: 15 min incline walk to finish the session",
  },
  {
    id: "conditioning",
    day: "Conditioning",
    short: "Cardio",
    iconName: "dayRun",
    accent: "#7C4DFF",
    title: "Conditioning",
    focus: "Calves, Power, Fat Burn",
    warmup: "5 min easy bike + ankle hops x20 + leg swings x10 each",
    exercises: [
      { name: "Jump Squat", videoId: "tZjZxrAeVjg", sets: 3, reps: "15", rest: "60s", muscle: "Quads, Glutes, Power", cue: "Land soft with bent knees, reset before each rep." },
      { name: "Push-Up", videoId: "WDIpL0pjun0", sets: 3, reps: "AMRAP", rest: "60s", muscle: "Chest, Core", cue: "Straight line head to heels, full range of motion." },
      { name: "Walking Lunge", videoId: "Pbmj6xPo-Hw", sets: 3, reps: "20 steps", rest: "60s", muscle: "Legs", cue: "Keep the pace steady — this is a conditioning set, not a max effort." },
      { name: "Standing Calf Raise", videoId: "SVtg-1loH4c", sets: 4, reps: "15–20", rest: "45s", muscle: "Calves", cue: "Full stretch at bottom, pause at the top squeeze." },
    ],
    cardioFinisher: "Finish with 10 min intervals: 30s hard / 90s easy on any machine",
  },
];

const NUTRITION_TIPS = [
  {
    title: "Calorie Balance",
    body: "To lose fat while building muscle, aim for a small calorie deficit (roughly 300–500 calories below maintenance). Too large a deficit makes it hard to build or even keep muscle.",
  },
  {
    title: "Protein First",
    body: "Target about 0.7–1g of protein per pound of bodyweight per day (or ~1.6–2.2g/kg). Protein preserves and builds muscle even while in a calorie deficit — prioritize it at every meal.",
  },
  {
    title: "Don't Fear Carbs & Fats",
    body: "Carbs fuel your gym sessions, fats support hormones. Fill remaining calories with whole foods: vegetables, fruit, whole grains, nuts, and healthy oils.",
  },
  {
    title: "Hydration & Sleep",
    body: "Aim for 7–9 hours of sleep and steady water intake. Recovery is where muscle is actually built — training just provides the stimulus.",
  },
  {
    title: "Progressive Overload",
    body: "Each week, aim to add a little weight, a rep, or better form on your lifts. Small consistent increases over months drive both the muscle and metabolism that support fat loss.",
  },
];
